### ISSUE TITLE
Create user interface module for flask webpage

### ISSUE THREAD

**Issue by Stewtec612** [Stewtec612/project_3--api-jordan-stewart-noelle-sif#6]
create a module that is to represent a webpage's user interface

the user will be able to enter their name

the user will select a zodiac sign from a drop down list

the user will click a button that loads the users name, the zodiac sign they selected, tarot card name and attributes, power animal name and picture, and horoscope 

give the user the option to display saved fortunes that are stored in the database

**Comment by uh5331tc** [comment]
Created user interface.
